version: '3.1'
services:
  go-emby2openlist:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    container_name: go-emby2openlist
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./openlist-local-tree:/app/openlist-local-tree
    ports:
      - 8095:8095 # http
